package com.speedystone.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ocrandtranslate.ocr.HistoryResponse;

import com.speedystone.greendaodemo.db.HistoryResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyResponseDaoConfig;

    private final HistoryResponseDao historyResponseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyResponseDaoConfig = daoConfigMap.get(HistoryResponseDao.class).clone();
        historyResponseDaoConfig.initIdentityScope(type);

        historyResponseDao = new HistoryResponseDao(historyResponseDaoConfig, this);

        registerDao(HistoryResponse.class, historyResponseDao);
    }
    
    public void clear() {
        historyResponseDaoConfig.clearIdentityScope();
    }

    public HistoryResponseDao getHistoryResponseDao() {
        return historyResponseDao;
    }

}
